development:
  MPESA_API_KEY: a0rdeuPwoSqGv0HIlGBqZeMEocwIfjha
  MPESA_API_SECRET: GC2ScUskImTOSaVR
  MPESA_API_PASSKEY: b87283b3be82ed37fdfbed3209156575757720419a85088aec920583d05bcabc

  MPESA_SANDBOX_API_KEY: TrnEPlNA2DD32e81MwGuqFm4Buliif5c
  MPESA_SANDBOX_API_SECRET: qz9R5oXJAA3IH3yu
  MPESA_SANDBOX_API_PASSKEY: b87283b3be82ed37fdfbed3209156575757720419a85088aec920583d05bcabc

  MPESA_B2C_API_KEY: H9sp7IZjvZofvKIqmbDMFGu39N95FOEj
  MPESA_B2C_API_SECRET: Rv52lKuXA0jfHBgE
  MPESA_B2C_API_PASSKEY: mdlhTIiKm9B2y9gLxqSXvK/a7IPzGfCfLxU4lPcBMh4ZSiEuVElydgkofl6dJTbHv4rgdPPz4+16JoWWrG/g0rPv6QWlBLnUpAroZgIrN/vLHuMGPXpUVUDV/zNXLq6LppXfOTIRWTzFex2KpBqcQInl2/AXu2WAUN+l3kp+b8S/cEgAF0vGmH8qKS210W1fguTX11GxVdR+hhCoJSioCVtKYeRRyJ7IbgJUd1P7LkkCicM0QMP6A6pa6MWqfS14uHZhziQZPkjgZCOIuRx7MHHDebyjOPR4LEtYO9c0/1A4tBpVPCdOT+vtUJ1I5jBbg0ipKTBv63dM0FK9H1y2Cw==

  C2B_PAYBILL: 4072015
  B2C_PAYBILL: 3012169
  C2B_USERNAME: sombo
  B2C_USERNAME: sombob2c

  BASE_URL: https://api.safaricom.co.ke
  TIMEOUT_URL: https://prycely.com/validation
  RESULT_URL: https://prycely.com/api/v1/mpesa/b2c
  CONFIRMATION_URL: https://prycely.com/thecalls/c2b
  VALIDATION_URL: https://prycely.com/thecalls/validation
  STK_CALLBACK: https://prycely.com/api/v1/mpesa/stk-callback

production:
  MPESA_API_KEY: a0rdeuPwoSqGv0HIlGBqZeMEocwIfjha
  MPESA_API_SECRET: GC2ScUskImTOSaVR
  MPESA_API_PASSKEY: b87283b3be82ed37fdfbed3209156575757720419a85088aec920583d05bcabc

  MPESA_SANDBOX_API_KEY: TrnEPlNA2DD32e81MwGuqFm4Buliif5c
  MPESA_SANDBOX_API_SECRET: qz9R5oXJAA3IH3yu
  MPESA_SANDBOX_API_PASSKEY: b87283b3be82ed37fdfbed3209156575757720419a85088aec920583d05bcabc

  MPESA_B2C_API_KEY: H9sp7IZjvZofvKIqmbDMFGu39N95FOEj
  MPESA_B2C_API_SECRET: Rv52lKuXA0jfHBgE
  MPESA_B2C_API_PASSKEY: mdlhTIiKm9B2y9gLxqSXvK/a7IPzGfCfLxU4lPcBMh4ZSiEuVElydgkofl6dJTbHv4rgdPPz4+16JoWWrG/g0rPv6QWlBLnUpAroZgIrN/vLHuMGPXpUVUDV/zNXLq6LppXfOTIRWTzFex2KpBqcQInl2/AXu2WAUN+l3kp+b8S/cEgAF0vGmH8qKS210W1fguTX11GxVdR+hhCoJSioCVtKYeRRyJ7IbgJUd1P7LkkCicM0QMP6A6pa6MWqfS14uHZhziQZPkjgZCOIuRx7MHHDebyjOPR4LEtYO9c0/1A4tBpVPCdOT+vtUJ1I5jBbg0ipKTBv63dM0FK9H1y2Cw==

  C2B_PAYBILL: 4072015
  B2C_PAYBILL: 3012169
  C2B_USERNAME: sombo
  B2C_USERNAME: sombob2c

  BASE_URL: https://api.safaricom.co.ke
  TIMEOUT_URL: https://prycely.com/validation
  RESULT_URL: https://prycely.com/api/v1/mpesa/b2c
  CONFIRMATION_URL: https://prycely.com/thecalls/c2b
  VALIDATION_URL: https://prycely.com/thecalls/validation
  STK_CALLBACK: https://prycely.com/api/v1/mpesa/stk-callback